// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoazbAyePL5arwkFqLWGa0X6WMhyIEM58',
    appId: '1:520544772825:web:4eff764746a2cbd308d4c8',
    messagingSenderId: '520544772825',
    projectId: 'dashboard-payakumbuh',
    authDomain: 'dashboard-payakumbuh.firebaseapp.com',
    storageBucket: 'dashboard-payakumbuh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBebzQq9ELzaLy0dH3vgR-HbbDcSHYjwn4',
    appId: '1:520544772825:ios:db171bff1016c20008d4c8',
    messagingSenderId: '520544772825',
    projectId: 'dashboard-payakumbuh',
    storageBucket: 'dashboard-payakumbuh.firebasestorage.app',
    iosBundleId: 'com.example.dashboardKotaPayakumbuh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBebzQq9ELzaLy0dH3vgR-HbbDcSHYjwn4',
    appId: '1:520544772825:ios:db171bff1016c20008d4c8',
    messagingSenderId: '520544772825',
    projectId: 'dashboard-payakumbuh',
    storageBucket: 'dashboard-payakumbuh.firebasestorage.app',
    iosBundleId: 'com.example.dashboardKotaPayakumbuh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoazbAyePL5arwkFqLWGa0X6WMhyIEM58',
    appId: '1:520544772825:web:a0e43855dbe399ee08d4c8',
    messagingSenderId: '520544772825',
    projectId: 'dashboard-payakumbuh',
    authDomain: 'dashboard-payakumbuh.firebaseapp.com',
    storageBucket: 'dashboard-payakumbuh.firebasestorage.app',
  );
}
